---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# SaviR

<!-- badges: start -->
<!-- badges: end -->

The goal of SaviR is to collect the functions needed to access and prepare various COVID data sources.

This package is divided into two main sections: analytical datasets and data visualizations.

## Installation

You can install the released version of SaviR from [Github](https://github.com/randyyee/SaviR) with:

``` r
devtools::install_github("randyyee/SaviR")
```

## COVAD - COVID Analytical Datasets

| Metadata Functions | Get Functions      | Calculation Functions | Production Functions |
|--------------------|--------------------|-----------------------|----------------------|
| get_one_table      | get_covid_sources  | calc_add_risk         | prod_sitrep          |
| get_country_coords | get_testing        |                       |                      |
|                    | get_vaccinations   |                       |                      |

* Metadata is stored in this package.

```{r eval=FALSE}
metadata <- onetable  
country_coordinates <- country_coords  
```

## COVAC - COVID Analytical Checks

IN DEVELOPMENT  

## COVIS - COVID Visualizations

| Plot Functions            | Map Functions    | Table Functions       |
|---------------------------|------------------|-----------------------|
| plot_epicurve             | map_template     | table_10mostcases     |
| plot_epicurve_ind         | map_burden       | table_10mostincidence |
| plot_epicurve_epidouble   | map_trend        | table_10percentchange |
| plot_epicurve_dailydouble | map_vaccinations | table_10vaccinations  |
| plot_riskmatrix           |                  |                       |
| plot_vaxcoverage          |                  |                       |
